name: CD AWS

on:
  push:
    tags:
      - distribute
  pull_request_target:
    types:
      - closed

jobs:
  build:
    if: ((github.event.pull_request.merged == true) || (github.event_name == 'push'))
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Checkout server
        uses: actions/checkout@v4
        with:
          ref: 'master'

      - name: Checkout submodule
        uses: actions/checkout@v4
        with:
          token: '${{ secrets.SUBMODULE_PAT }}'
          repository: 'capstone-shop/${{ secrets.SUBMODULE_REPOSITORY_NAME }}'
          path: src/main/resources/settings

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.10
          cache-encryption-key: ${{ secrets.GradleEncryptionKey }}

      - run: gradle build --configuration-cache -x test
      - run: docker build -t shop-server .
      - run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - run: docker tag shop-server ${{ secrets.DOCKER_USERNAME }}/shop-server:latest

      - name: docker push
        run: docker push ${{ secrets.DOCKER_USERNAME }}/shop-server:latest

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_SSH_SERVER }}
          username: ${{ secrets.EC2_SSH_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            CONTAINER_ID=$(sudo docker ps -q --filter "ancestor=${{ secrets.DOCKER_USERNAME }}/shop-server")
            
            if [ ! -z "$CONTAINER_ID" ]; then
              sudo docker stop $CONTAINER_ID
              sudo docker rm $CONTAINER_ID
              sudo docker system prune
            fi
            
            docker pull ${{ secrets.DOCKER_USERNAME }}/shop-server:latest
            nohup docker run -p 80:80 -e TZ=Asia/Seoul ${{ secrets.DOCKER_USERNAME }}/shop-server:latest > shop-server.log 2>&1 &