name: CD AWS

on:
  push:
    tags:
      - distribute
  pull_request_target:
    types:
      - closed

jobs:
  build:
    if: ((github.event.pull_request.merged == true) || (github.event_name == 'push'))
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Checkout server
        uses: actions/checkout@v4
        with:
          ref: 'master'

      - name: Checkout submodule
        uses: actions/checkout@v4
        with:
          token: '${{ secrets.SUBMODULE_PAT }}'
          repository: 'capstone-shop/${{ secrets.SUBMODULE_REPOSITORY_NAME }}'
          path: src/main/resources/settings

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.10
          cache-encryption-key: ${{ secrets.GradleEncryptionKey }}

      - run: gradle build --configuration-cache -x test

      - name: deploy file to server
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: '${{ secrets.EC2_SSH_USER }}'
          server: '${{ secrets.EC2_SSH_SERVER }}'
          ssh_private_key: ${{ secrets.EC2_SSH_KEY }}
          local_path: './build/lib/*.jar'
          remote_path: '~/'
          sftpArgs: '-o ConnectTimeout=5'

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_SSH_SERVER }}
          username: ${{ secrets.EC2_SSH_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            pgrep -of java | xargs kill -9 2> /dev/null
            rm server.log 2> /dev/null
            nohup java -jar *.jar > server.log 2>&1 &